#pragma once

#include <stdio.h>


#define custom_PADS_BANK0_GPIO_OFFSET _u(0x00000004)
#define PUE_val 1<<4

enum pin_func 
{
    JTAG,
    SPI,
    UART,
    I2C,
    PWM,
    SIO,
    PIO0,
    PIO1,
    CLOCK,
    USB,
    NONE = 0x1f
};



/*
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_RESET  _u(0x1f)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_BITS   _u(0x0000001f)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_MSB    _u(4)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_LSB    _u(0)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_ACCESS "RW"
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_VALUE_JTAG_TMS _u(0x00)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_VALUE_SPI0_SS_N _u(0x01)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_VALUE_UART0_RX _u(0x02)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_VALUE_I2C0_SCL _u(0x03)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_VALUE_PWM_B_0 _u(0x04)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_VALUE_SIO_1 _u(0x05)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_VALUE_PIO0_1 _u(0x06)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_VALUE_PIO1_1 _u(0x07)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_VALUE_USB_MUXING_VBUS_DETECT _u(0x09)
#define IO_BANK0_GPIO1_CTRL_FUNCSEL_VALUE_NULL _u(0x1f)
*/